route:
  group_by: ['cluster']
  receiver: "webhook-receiver-up"
  routes:
  - match:
      severity: 'high'
    receiver: "webhook-receiver-up"
receivers:
- name: "webhook-receiver-up"
  webhook_configs:
  - url: 'http://172.31.14.53:5000/post'
    send_resolved: true
