version: '2'

services:
  #seed:
  #  image: docker-compose-akka-cluster:0.1-SNAPSHOT
  # hostname: akkaseed
  #  command: -Dakka.remote.netty.tcp.hostname=akkaseed

  #node:
  #  image: docker-compose-akka-cluster:0.1-SNAPSHOT
  #  links:
  #    - "seed:akkaseed"

  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888


  akkaseed:
      build:
        context: /root/work/tally-gsp-demo
        dockerfile: src/main/docker/services/akkaseedservice
      image: akkaseed
      #hostname: backend
      #links:
        #- "seed:akkaseed"
      dns: 172.31.15.183
      dns_search: service.consul

  backend:
    build:
      context: /root/work/tally-gsp-demo
      dockerfile: src/main/docker/services/backendservice
    image: backend
    #hostname: backend
    #links:
      #- "seed:akkaseed"
    dns: 172.31.15.183
    dns_search: service.consul

  frontend:
    build:
      context: /root/work/tally-gsp-demo
      dockerfile: src/main/docker/services/frontendservice
    image: frontend
    #image: frontend
    #hostname: frontend
    ports:
      - "8082:8082"
    #links:
      #- "seed:akkaseed"
    dns: 172.31.15.183
    dns_search: service.consul

  proxy:
    build:
      context: /root/work/tally-gsp-demo/src/main/docker/services/docker-flow-proxy
      dockerfile: .
    image: proxy

networks:
  default:
    external:
      name: my-net